### ISSUE TITLE
Question: Android kernel support?

### ISSUE THREAD

**Issue by smeenai** [google/gwpsan#9]
The documentation says that Linux kernel version 6.4 or above has all the required support patches. I don't have a recent Pixel device on hand to verify right now, but from what I can find online, current Pixel phones come with Linux 5.15, with a possible upgrade to Linux 6.1 on the way. Does the Android Common Kernel have all the relevant patches backported by any chance, and if so, which minimum Android kernel version would you recommend?

**Comment by melver** [comment]
> Does the Android Common Kernel have all the relevant patches backported by any chance [...]

Not that I'm aware of.

You may get lucky with Linux 6.1. It already includes all patches we listed, except [posix-timers: Prefer delivery of signals to the current thread](https://git.kernel.org/torvalds/c/bcb7ee79029d). GWPSan includes code that works around the absence of that last patch, and its absence is less severe performance-wise than all the other patches.

If, on the platform of interest, you are able to run the [tests](https://github.com/google/gwpsan?tab=readme-ov-file#testing),  and they pass, you can try if using GWPSan works for your usecase performance-wise.

**Comment by smeenai** [comment]
Thank you!
